In [1]:
import numpy as np

In [20]:
myShape = (2, 2, 2, 3)

In [24]:
dat = np.arange(24)
dat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
reshaped = dat.reshape([3, 2, 2, 2])
reshaped

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [38]:
# if rolling using last axis, items get regrouped by the positions they have in the lowest level arrays
# think of 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22
# then this group gets regrouped by the larger groups they belong to before

transposed = reshaped.transpose((3,0,1,2)) # 2 x 3 x 2 x 2
transposed

array([[[[ 0,  2],
         [ 4,  6]],

        [[ 8, 10],
         [12, 14]],

        [[16, 18],
         [20, 22]]],


       [[[ 1,  3],
         [ 5,  7]],

        [[ 9, 11],
         [13, 15]],

        [[17, 19],
         [21, 23]]]])

In [40]:
rolled = np.rollaxis(reshaped, 3, 1)
rolled

array([[[[ 0,  2],
         [ 4,  6]],

        [[ 1,  3],
         [ 5,  7]]],


       [[[ 8, 10],
         [12, 14]],

        [[ 9, 11],
         [13, 15]]],


       [[[16, 18],
         [20, 22]],

        [[17, 19],
         [21, 23]]]])

In [28]:
reordered = transposed[:,:,:,::-1]
reordered

array([[[[ 2,  0],
         [ 6,  4]],

        [[10,  8],
         [14, 12]],

        [[18, 16],
         [22, 20]]],


       [[[ 3,  1],
         [ 7,  5]],

        [[11,  9],
         [15, 13]],

        [[19, 17],
         [23, 21]]]])